XW-3349 | Preserve scroll position when closing lightbox.
Wikia/mobile-wiki pull request #102
Opened 2017-05-25 09:49 UTC by JamesHawking

## Links

https://wikia-inc.atlassian.net/browse/XW-3349

## Description

Preserve scroll position when closing lightbox.
Upgrade ember-router-scroll to 0.2.0.

## Reviewers

@Wikia/x-wing

2017-05-25 10:00 UTC, hakubo requested changes

2017-05-25 10:00 UTC, hakubo commented on app/controllers/wiki-page.js
> +		 * @param lightboxType
missing types

2017-05-25 10:00 UTC, hakubo commented on app/routes/wiki-page.js
> +		 * @param controller
missing type

2017-05-25 10:07 UTC, hakubo approved these changes

2017-05-25 10:09 UTC, rybmat approved these changes

2017-05-25 10:19 UTC, rogatty commented on app/routes/wiki-page.js
> +		 */
`@returns {void}`

2017-05-25 10:21 UTC, rogatty commented on app/routes/wiki-page.js
> +				this.get('controller').send('closeLightbox');
Is this needed? There is exactly the same thing in `routes/application.js`

2017-05-26 11:24 UTC, ludwikkazmierczak commented
Tested and Accepted

2017-05-26 11:25 UTC, merged