XF-575 | Using appName for internal calls header
Wikia/mobile-wiki pull request #1023
Opened 2018-09-05 14:39 UTC by bkoval

@Wikia/x-wing

2018-09-05 19:44 UTC, hakubo commented on app/models/user.js
> +      headers: { 'X-Wikia-Internal-Request': this.runtimeConfig.environment.appName },
hmm I knew it'll be confusing
we'll have to rethink that...
but

whatever is set in config/environment.js
you 'just' import
import config from '..'';

2018-09-06 08:55 UTC, rybmat approved these changes

2018-09-06 09:05 UTC, xkxd approved these changes

2018-09-06 12:21 UTC, hakubo commented on package.json
> +    "ember-cli-sass": "7.1.7",
?

2018-09-06 12:21 UTC, hakubo commented on package.json
> +    "ember-router-scroll": "0.7.1",
?

2018-09-06 12:21 UTC, hakubo requested changes
package.json should not be part of this change

2018-09-07 07:25 UTC, bkoval commented
Weeeeeeeird. Removed the package.json changes anyway ;)

2018-09-10 08:33 UTC, hakubo approved these changes

2018-09-11 13:17 UTC, merged