XW-3672 | Power mobile recirc unit with LiftIgniter
Wikia/mobile-wiki pull request #117
Opened 2017-07-05 13:14 UTC by JamesHawking

## Links

* https://wikia-inc.atlassian.net/browse/XW-3672

## Description

AC:
* Recommendations are powered by liftigniter
* Verify that Sponsored Content correctly appears Options

## Reviewers

@Wikia/x-wing

2017-07-05 13:27 UTC, rogatty commented on app/services/liftigniter.js
> +const localStorageAdapter = require('mobile-wiki/utils/local-storage-connector').localStorageAdapter;
Use `import localStorageConnector from '../utils/local-storage-connector';`

2017-07-05 13:27 UTC, rogatty commented on app/inline-scripts/tracking-liftigniter.js
> +})(window, document, 'script', '//cdn.fandommetrics.com/l9ehhrb6mtv75bp2.js', '$p');
Can we use `liftIgniter` instead of `$p`?

2017-07-05 13:29 UTC, rogatty commented on app/index.html
> +{{content-for 'tracking-liftigniter'}}
We keep the business-critical scripts here. Can we move this just above `{{content-for 'body-footer'}}`?

2017-07-05 13:31 UTC, rogatty commented on app/components/recirculation-prefooter.js
> +const recircItemsCount = 10;
Let's put it inside the component or move config here. For consistency.

2017-07-05 16:23 UTC, rogatty commented on app/services/liftigniter.js
> +		const deferred = $.Deferred(),
Let's use Ember's `RSVP.defer()`, see https://github.com/tildeio/rsvp.js/#deferred

2017-07-05 16:25 UTC, rogatty commented on app/styles/component/_recirculation.scss
> +	&--anchor {
We don't use the double dash.

2017-07-05 16:26 UTC, rogatty commented on app/styles/component/_recirculation.scss
> +	&--is-video {
`&.is-video`?

2017-07-05 16:26 UTC, rogatty commented on app/templates/components/recirculation-prefooter.hbs
> +				<!--This 'a' tag is required by liftigniter's js lib in order to properly set tracking for elements-->
`a` or `div`?

2017-07-05 16:28 UTC, rogatty commented on app/components/recirculation-prefooter.js
> +						title: this.get('i18n').t('recirculation.trending-fandom-articles'),
Why not use it directly in the template?

2017-07-06 08:37 UTC, rybmat commented on app/templates/components/recirculation-prefooter.hbs
> +				<!--This 'a' tag is required by liftigniter's js lib in order to properly set tracking for elements-->
`a`, `div` is not needed here at all

2017-07-06 09:58 UTC, hakubo commented on app/services/liftigniter.js
> +		const deferred = RSVP.defer(),
more common way of ding this is
return RSVP.Promise((resolve, reject) {
...
resolve(response)
})

but I would not change it now,

2017-07-06 10:01 UTC, hakubo requested changes

2017-07-06 10:01 UTC, hakubo commented on app/styles/component/_recirculation.scss
> +	  color: $wds-color-black;
spaces

2017-07-06 11:03 UTC, hakubo approved these changes

2017-07-06 12:04 UTC, rogatty approved these changes

2017-07-07 15:32 UTC, merged