Show wikia.org migration banner, PLATFORM-3967
Wikia/mobile-wiki pull request #1475
Opened 2019-03-13 11:30 UTC by abador

## Description
Enable messages about wikia.org migration. You need to set up flags to enable messages. Set wgWikiaOrgMigrationScheduled' or wgWikiaOrgMigrationDone to see standard message. Similar to fandom.com migration messages

2019-03-14 14:35 UTC, themech requested changes

2019-03-14 14:35 UTC, themech commented on app/mixins/wiki-page-handler.js
> +console.log("===============================================",query);
looks like debugging leftovers

2019-03-15 06:22 UTC, abador commented on app/mixins/wiki-page-handler.js
> +console.log("===============================================",query);
missed that :/

2019-03-15 07:50 UTC, themech approved these changes

2019-03-18 08:50 UTC, merged