[ADEN-9068] GAM lazy loading enabled
Wikia/mobile-wiki pull request #1697
Opened 2019-07-19 07:09 UTC by Loczi94

Explanation:
To enable GAM lazy loading:
- class 'hide' has to be removed for bottom_leaderboard, top_boxad and incontent_boxad_1,
- flag disablePushOnScroll for incontent-boxad_1 has to be true,
- option incontentBoxad1EagerLoading has to be on.

2019-07-19 11:06 UTC, bckatarzyna requested changes

2019-07-19 11:06 UTC, bckatarzyna commented on app/modules/ads/slots.js
> +          disablePushOnScroll: true,
It is already set in setup.js:158, you can remove it now

2019-07-22 08:32 UTC, bckatarzyna approved these changes

2019-07-22 13:23 UTC, bckatarzyna approved these changes

2019-07-24 07:56 UTC, dmnsobczak approved these changes

2019-07-24 08:50 UTC, merged