XW-3104 | Change handling of ogg/ogv files
Wikia/mobile-wiki pull request #176
Opened 2017-09-27 15:22 UTC by JamesHawking

## Links
[Ticket](https://wikia-inc.atlassian.net/browse/XW-3104)

## Reviewers

@Wikia/x-wing

2017-09-28 13:50 UTC, rybmat requested changes
please add support also on File pages i.e. /wiki/File:Example.ogg

2017-09-28 14:37 UTC, rybmat approved these changes

2017-09-28 16:04 UTC, xkxd commented on bower.json
> +    "design-system": "wikia/design-system#XW-3104",
remember to release design system

2017-09-28 16:04 UTC, xkxd approved these changes

2017-09-29 12:38 UTC, merged

2017-10-02 08:54 UTC, rogatty commented on app/components/article-media-thumbnail.js
> +			return this.get('type') === 'video' || this.get('isOgg') && this.get('title');
@Wikia/x-wing this should be `(this.get('type') === 'video' || this.get('isOgg')) && this.get('title')`