Cake 5273 | Design Modification to Watch Now Module
Wikia/mobile-wiki pull request #1873
Opened 2019-11-06 19:41 UTC by cschucode

## Links

* http://wikia-inc.atlassian.net/browse/CAKE-5273
* parent ticket: http://wikia-inc.atlassian.net/browse/CAKE-5251

## Description

In order to place the "Watch Now" module, I used a `setInterval` to wait for the **top-leaderboard** ad to appear before rendering.

Note: 
This does move Top Leaderboard Ad, so would request Ad-Eng team to run tests before merging.

## Reviewers

Use `@` mentions here. Alternatively, assign the pull request to a person.

2019-11-06 21:59 UTC, mklucsarits requested changes
I don't think this is an ideal solution. We should figure out why the code as written is placing the ad above "watch show" when it's supposed to load it outside/after `.portable-infobox-wrapper` (https://github.com/Wikia/mobile-wiki/blob/dev/app/services/ads/ad-slot-builder.js#L36). Additionally, waiting 5 seconds is an eternity in the mobile web world. If the ad doesn't load because the user is logged in, there's a good chance they'll have already scrolled the page and won't see "watch show" at all by the time it loads.

2019-11-06 22:55 UTC, cschucode commented
I agree and after another look, it appears that the ordering of the `handleWatchShow` can be moved down to achieve the desired effect without messing with or relying on ad code.

2019-11-06 23:55 UTC, mklucsarits approved these changes

2019-11-07 23:54 UTC, mklucsarits approved these changes

2019-11-08 00:29 UTC, merged