Cake 5678 - Create new Campaign for HBO Max in Mobile and Desktop in-content Affiliate units
Wikia/mobile-wiki pull request #2220
Opened 2020-05-19 02:02 UTC by unijuglr

## Links

* https://wikia-inc.atlassian.net/browse/CAKE-5678

## Description
Adding config and a slight template addition to support HBO MAX campaign
Can go live without concern, because it will be controlled by db rows being added at launch time

## Reviewers

Use `@` mentions here. Alternatively, assign the pull request to a person.
@Wikia/cake

2020-05-19 18:46 UTC, cschucode commented on app/services/affiliate-slots-units.json
> +    "subheading": "START YOUR FREE TRAIL",
TRAIL or TRIAL?

2020-05-19 18:46 UTC, cschucode commented on app/services/affiliate-slots-units.json
> +    "extra_disclaimer": "Free trail for new customers only. Restrictions Apply."
(see above)

2020-05-19 18:48 UTC, cschucode commented on app/services/affiliate-slots-units.json
> +  {
Did this get added a second time?

2020-05-19 18:48 UTC, cschucode commented on app/services/affiliate-slots-units.json
> +    "category": "ddb-test-unit-id",
Looks like we already have this unit.

2020-05-19 18:50 UTC, cschucode requested changes
Requested:
* fix typos
* remove extra unit

2020-05-19 21:28 UTC, unijuglr commented on app/services/affiliate-slots-units.json
> +    "category": "ddb-test-unit-id",
weird...

2020-05-20 17:49 UTC, cschucode commented
Are we going to need a big unit as well? There should be two for every category/campaign. One with the "isBig" set to `true` and one without it for the `post-search-results` unit?

2020-05-20 18:14 UTC, cschucode approved these changes
LGTM.

2020-05-20 19:52 UTC, merged