XW-4212 | placeholder for featured video
Wikia/mobile-wiki pull request #229
Opened 2017-11-07 16:43 UTC by rybmat

## Links

* https://wikia-inc.atlassian.net/browse/XW-4212

## Description

Adding placeholder for featured video to avoid "jumping effect" on articles when player is loading

## Reviewers

Use `@` mentions here. Alternatively, assign the pull request to a person.

2017-11-07 17:52 UTC, hakubo requested changes

2017-11-07 17:52 UTC, hakubo commented on app/components/article-featured-video-jwplayer.js
> +		return this.get('model').embed.jsParams.playlist[0].image;
You can put whole path to get for safer access

2017-11-07 17:52 UTC, hakubo commented on app/styles/component/_article-featured-video-jwplayer.scss
> +	height: calc(100vw * 9 / 16);
Alphabet!

2017-11-08 08:10 UTC, latata approved these changes

2017-11-08 08:58 UTC, hakubo approved these changes

2017-11-08 17:30 UTC, merged