ADEN-10737 add RealVu
Wikia/mobile-wiki pull request #2416
Opened 2020-12-29 13:00 UTC by KonradLinkowski

## Links

https://wikia-inc.atlassian.net/browse/ADEN-10737

## Description

Add RealVu to mobile-wiki

2020-12-29 13:09 UTC, dmnsobczak commented on app/modules/ads/fallback-config.json
> +    "icRealVu": false,
Pls remove. Jenkins is managing this file.

2020-12-29 13:09 UTC, dmnsobczak commented on app/modules/ads/core/stable-ads.js
> +    realVu.call();
Let's move it to `callExternalTrackingServices()`

2020-12-29 14:18 UTC, dmnsobczak requested changes
There are no RealVu id in ad-context:
https://github.com/Wikia/mobile-wiki/blob/584fd2e09b5b6d0baa834be345a93d73c6a54a0a/app/modules/ads/ad-context.js

2020-12-30 06:56 UTC, dmnsobczak approved these changes

2020-12-30 11:36 UTC, nandy-andy approved these changes

2020-12-30 13:38 UTC, merged