XW-4547 | Featured Video Attribution
Wikia/mobile-wiki pull request #374
Opened 2018-01-29 11:29 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-4547
@Wikia/x-wing

2018-01-29 15:55 UTC, hakubo requested changes

2018-01-29 15:55 UTC, hakubo commented on app/components/article-featured-video.js
> +	hasAttribution: computed('currentVideoDetails.{username,userUrl,userAvatarUrl}', function () {
https://emberjs.com/api/ember/2.18/classes/@ember%2Fobject%2Fcomputed/methods/and?anchor=and

2018-01-30 08:03 UTC, hakubo commented on app/components/article-featured-video.js
> +	attributionAvatarUrl: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==',
we use the same gif in about 7 places
what do you think in moving it to
https://github.com/Wikia/mobile-wiki/blob/dev/app/utils/thumbnail.js ?

2018-01-30 08:04 UTC, hakubo commented on app/components/article-featured-video.js
> +	currentVideoDetails: oneWay('initialVideoDetails'),
nice use of oneWay 👍

2018-01-30 08:06 UTC, hakubo commented on app/templates/components/article-featured-video.hbs
> +		<div class="article-featured-video__attribution-inner-container">
is it just github? or something weird happend with spaces here?

2018-01-30 09:27 UTC, hakubo approved these changes

2018-01-31 10:52 UTC, bkoval approved these changes

2018-01-31 20:22 UTC, merged