XW-4422 | Featured Video - On scroll unit
Wikia/mobile-wiki pull request #381
Opened 2018-01-30 18:55 UTC by latata

https://wikia-inc.atlassian.net/browse/XW-4422
@Wikia/x-wing

2018-01-30 19:32 UTC, hakubo commented on app/components/article-featured-video.js
> +	isOnScrollActiveObserver: observer('isOnScrollActive', function () {
this could be a typical function that you can call when needed
I think this would be much cleaner to read

2018-01-30 19:40 UTC, hakubo commented on app/components/article-featured-video.js
> +			requiredScrollDelimiter = this.$().offset().top,
kudos for not using jquery in this PR
what do you think about replacing this with
this.element.getBoundingClientRect().top?

2018-01-31 10:47 UTC, bkoval requested changes

2018-01-31 10:47 UTC, bkoval commented on app/components/article-featured-video.js
> +		const currentVideoDuration = this.get('currentVideoDetails.duration');
new line after const

2018-01-31 10:47 UTC, bkoval commented on app/components/article-featured-video.js
> +		document.body.classList.add('featured-video-on-scroll-active');
Don't we want bem here?

2018-01-31 10:47 UTC, bkoval commented on app/components/article-featured-video.js
> +			document.body.classList.remove('featured-video-on-scroll-active');
How about defining a property for this classname, so that we can reuse across the component?

2018-01-31 10:47 UTC, bkoval commented on app/styles/component/_article-featured-video.scss
> +		color: #999;
Don't we have a design system variable for this color? :D

2018-02-01 11:26 UTC, bkoval approved these changes

2018-02-01 11:45 UTC, hakubo approved these changes

2018-02-03 12:33 UTC, merged