XW-4593 | jquery less modules/ads
Wikia/mobile-wiki pull request #390
Opened 2018-02-02 09:16 UTC by hakubo

We'll be removing jquery from mobile-wiki
this is one of PRs that makes us ready for this

2018-02-02 09:42 UTC, kvas-damian commented on app/modules/ads.js
> +			hasPageHeader = !!document.getElementsByClassName('.wiki-page-header'),
```
!![]
//true
```
Please make sure that conditions still return the same value

2018-02-02 11:38 UTC, kvas-damian commented on app/modules/ads.js
> +		const numberOfSections = document.querySelector('.article-content > h2').length,
Very likely, this one will be evaluated to `undefined`

2018-02-02 11:38 UTC, kvas-damian commented on app/modules/ads.js
> +				firstSection.length &&
it will always evaluate to `undefined`

2018-02-02 11:41 UTC, kvas-damian requested changes
Please fix pointed problems with missing `length` attribute on `DomNode`

2018-02-02 13:57 UTC, kvas-damian approved these changes
Please run Ads selenium tests before merging

2018-02-05 08:59 UTC, latata commented on app/modules/ads.js
> +				firstSection.getBoundingClientRect().top + document.body.scrollTop
I've extracted offset to module function in `XW-4591`, we could use it here.

2018-02-06 08:58 UTC, merged