XW-4679 | References do not work since the target anchor is in a collapsed section.
Wikia/mobile-wiki pull request #472
Opened 2018-03-02 18:47 UTC by kolek7

## Links

https://wikia-inc.atlassian.net/browse/XW-4679

## Description
References in articles don't work because they invariably point to a collapsed section.

2018-03-05 08:21 UTC, hakubo requested changes

2018-03-05 08:21 UTC, hakubo commented on app/components/article-content.js
> +					element.onclick = function () {
create one click() handler on whole article-content
and handle all clicks in there

2018-03-05 08:21 UTC, hakubo commented on app/components/article-content.js
> +								currentHeader.click();
although this works 
it's rather ugly
you could extract body of the click handler of a header
and call it directly

2018-03-05 08:21 UTC, hakubo commented on app/components/article-content.js
> +							if (currentHeader.className !== 'open-section') {
you can use classList API

2018-03-05 09:35 UTC, latata commented on app/components/article-content.js
> +					'ol[class*="references"] ' +
do we need such a specific selector?

2018-03-05 09:35 UTC, latata commented on app/components/article-content.js
> +				citeRefs = this.element.querySelectorAll('a[href*="cite_note"]'),
I'd go with `.reference a[href^=#cite_note-]` selector

2018-03-05 09:35 UTC, latata commented on app/components/article-content.js
> +				referencesList = this.element.querySelectorAll('ol[class*="references"]');
Why not `ol.references`?

2018-03-05 19:30 UTC, hakubo commented on app/components/article-content.js
> +				const element = event.target.closest('a[href^="#cite_ref-"]'),
I know we are still not consitent with that 
but per our current js style guide- https://github.com/Wikia/javascript-style-guide#variables
one const per variable

we need to finally work on our eslinter...

2018-03-05 19:32 UTC, hakubo commented on app/components/article-content.js
> +				const element = event.target.closest('a[href^="#cite_ref-"]'),
also you get this element twice, could be optimized to get it just once maybe?

2018-03-05 19:33 UTC, hakubo commented on app/components/article-content.js
> +					let currentHeader = document.getElementById(closest.previousElementSibling.id);
getElementById can return null

@bkoval maybe we should write a small wrapper for common getters?

2018-03-05 19:34 UTC, hakubo commented on app/components/article-content.js
> +					if (!currentHeader.classList.contains('open-section')) {
you don't have to check if it contains the class
add - will add only once

2018-03-05 19:37 UTC, hakubo commented on app/components/article-content.js
> +					header = header[0].closest('section[id*="section"]').previousElementSibling;
try not to reuse variables, having two separate ones should make the code easier to understand

2018-03-05 19:38 UTC, hakubo commented on app/components/article-content.js
> +		handleReferences(event) {
you can use object destructuring here
`{target}`
and then you can access it 'directly'

2018-03-05 19:38 UTC, hakubo commented
This is starting to look good! Thanks!

2018-03-06 08:35 UTC, latata commented on app/components/article-content.js
> +					let currentHeader = document.getElementById(closest.previousElementSibling.id);
I guess `closest.previousElementSibling === document.getElementById(closest.previousElementSibling.id)`.

2018-03-06 08:35 UTC, latata commented on app/components/article-content.js
> +					let currentHeader = document.getElementById(closest.previousElementSibling.id);
use `const` if you don't change variable's value.

2018-03-06 08:35 UTC, latata commented on app/components/article-content.js
> +				let header = this.element.querySelectorAll('ol.references');
I wonder if article can have more than one references section. If yes, we should find the right section first.

2018-03-08 16:57 UTC, hakubo commented on app/components/article-content.js
> +		handleCiteNotes(event) {
handleCiteNotes({target}) { - you can destructure arguments

2018-03-08 16:58 UTC, hakubo commented on app/components/article-content.js
> +					const citeNoteList = this.element.querySelectorAll(target.hash);
since we always need first citeNoteList - maybe we should use querySelector?

2018-03-08 16:59 UTC, hakubo commented on app/components/article-content.js
> +						currentSection = citeNoteList[0].closest('section[id*="section"]');
you could 'let' here
as we don't need the var outside this if

2018-03-08 17:02 UTC, hakubo commented on app/components/article-content.js
> +						const referencesSection = referenceListItem[0].parentElement.closest('section[id*="section"]');
why do you need to get parentElement? can't this just run on referenceListItem?

2018-03-08 17:03 UTC, hakubo commented on app/components/article-content.js
> +						if (referencesSection) {
this part of code looks very similar to the code from the other function
maybe you could extract openining a section to another method? :)

2018-03-08 20:58 UTC, bkoval requested changes
Great job! A few minor comments but overall it looks fine!

2018-03-08 20:58 UTC, bkoval commented on app/components/article-content.js
> +					const referenceListItem = this.element.querySelector(target.hash);
Make sure to leave one blank line after declarations of consts / lets.

2018-03-08 20:58 UTC, bkoval commented on app/components/article-content.js
> +				if (target.hash.search('#cite_ref-') === 0) {
How about combining these two if's into one? This way we could gain some readability as there would be less indentations:

```
if (target.nodeName === 'A' && target.hash.search('#cite_ref-') === 0) {
```

2018-03-08 20:58 UTC, bkoval commented on app/components/article-content.js
> +					if (header) {
What if the ref is in the "zero section" (the article section that starts directly below the article title and ends before the first H2). This section is always expanded, even on mobile.

I would consider checking if tagName === 'H2' before appending the 'open-section' class. What do you think?

2018-03-08 20:58 UTC, bkoval commented on app/components/article-content.js
> +						header.classList.add('open-section');
What about scrolling the ref into view after expanding the section? Does that work now based on url hash or should we think of adding some JS to scroll the given ref into view?

2018-03-12 08:49 UTC, xkxd approved these changes

2018-03-12 08:49 UTC, xkxd commented on app/components/article-content.js
> +			if (element) {
this check is redundant. if "element" will be null/undefined it'll throw a TypeError in 
```const offsetY = reference.getBoundingClientRect().top + window.scrollY;```
anyway

\+ please add ```@param {Element} element``` to jsdocs

2018-03-12 08:49 UTC, xkxd commented on app/components/article-content.js
> +		 * @returns {void}
please add `@param {MouseEvent} event` to jsdocs

2018-03-12 10:24 UTC, bkoval approved these changes

2018-03-13 12:34 UTC, merged