XW-4743 | Fandom App webview events tracking added.
Wikia/mobile-wiki pull request #493
Opened 2018-03-14 12:39 UTC by kolek7

## Links

https://wikia-inc.atlassian.net/browse/XW-4743

## Reviewers

@Wikia/x-wing

2018-03-14 12:55 UTC, rybmat requested changes

2018-03-14 12:55 UTC, rybmat commented on app/utils/track.js
> +	const appOrMercury = (isFandomApp === 'true' ? 'fandom-app-' : 'mercury-');
can we name this const differently? `categoryPrefix` for example?

2018-03-14 12:55 UTC, rybmat commented on app/utils/track.js
> +		category = params.category ? appOrMercury + params.category : null,
we can use string templates here `${categoryPrefix}-${params.category}`
(note: remove trailing `-` from the categoryPrefix const)

2018-03-14 13:17 UTC, hakubo approved these changes

2018-03-14 13:18 UTC, hakubo commented on app/utils/track.js
>  	const trackingMethod = params.trackingMethod || 'both',
while you're at it could you split to const per variable?

2018-03-14 13:19 UTC, hakubo commented on app/utils/track.js
> +	const isFandomApp = new URL(window.location).searchParams.get('mobile-app') === 'true';
this function runs also on Fastboot
on  line 133 and 137 there are neede checks - this should probably happen after these lines

2018-03-14 13:22 UTC, xkxd commented on app/utils/track.js
> +	const isFandomApp = new URL(window.location).searchParams.get('mobile-app') === 'true';
i'd suggest moving those fastboot/window checks at the top of `track` method

2018-03-14 14:42 UTC, rybmat approved these changes

2018-03-15 13:11 UTC, hakubo approved these changes

2018-03-16 10:01 UTC, merged