ADEN-7119 Make ads compliant with ad-engine v12.0.0 and repeat incontent boxad before each section
Wikia/mobile-wiki pull request #736
Opened 2018-05-30 13:17 UTC by fraszczakszymon

## Links

* http://wikia-inc.atlassian.net/browse/ADEN-7119
* https://github.com/Wikia/ad-engine/pull/139

2018-06-01 12:50 UTC, dmnsobczak approved these changes

2018-06-04 07:22 UTC, hakubo requested changes
package-lock in a wrong state
please run 
npm i -g npm@latest
npm cache clean --force
npm install

2018-06-04 11:11 UTC, hakubo approved these changes

2018-06-04 11:17 UTC, dmnsobczak commented
LGTM.

2018-06-06 12:08 UTC, merged