XW-5098: add addQueryParameters method, update DS
Wikia/mobile-wiki pull request #790
Opened 2018-07-09 06:52 UTC by rybmat

## Links

* http://wikia-inc.atlassian.net/browse/XW-5098

## Reviewers

@Wikia/x-wing

2018-07-09 08:27 UTC, hakubo requested changes

2018-07-09 08:27 UTC, hakubo commented on app/utils/url.js
> +export function addQueryParams(url, params = {}) {
Test please 🙏

2018-07-09 09:06 UTC, rybmat commented on app/utils/url.js
> +export function addQueryParams(url, params = {}) {
@hakubo done

2018-07-09 12:36 UTC, bkoval approved these changes

2018-07-10 07:12 UTC, hakubo approved these changes

2018-07-10 07:43 UTC, JamesHawking approved these changes

2018-07-10 08:21 UTC, merged