XW-5117 | New styling for Featured Video on scroll
Wikia/mobile-wiki pull request #850
Opened 2018-07-26 13:38 UTC by bkoval

@Wikia/x-wing

2018-07-26 13:58 UTC, latata approved these changes

2018-07-26 13:58 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +			opacity: 1;
I think, we don't need it.

2018-07-26 13:58 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +			max-height: 0;
remove `max-height`

2018-07-26 13:58 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +			max-height: 200px;
remove `max-height`

2018-07-26 13:58 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +	&.is-on-scroll-active &__title {
remove `&.is-on-scroll-active`

2018-07-26 13:58 UTC, latata requested changes
Approve missclick ;)

2018-07-27 06:39 UTC, rybmat approved these changes

2018-07-27 06:39 UTC, rybmat commented on app/styles/component/_article-featured-video.scss
> +		background: #272727;
what is that color? maybe it should be some standard wds color with opacity?

2018-07-27 06:39 UTC, rybmat commented on app/templates/components/article-featured-video.hbs
> +				<h1 class="article-featured-video__title wds-font-size-s wds-font-weight-bold">{{currentVideoDetails.title}}</h1>
is it ok to use h1 here? shouldn't it be h2? just asking, no strong opinion

2018-07-27 09:42 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +		background: #272727;
If we don't have this color in DS let's ask Derek about it.

2018-07-27 09:42 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +		.jw-state-paused ~ .article-featured-video__details-wrapper {
you can put these styles inside `.jw-state-paused {`

2018-07-27 09:42 UTC, latata commented on app/styles/component/_article-featured-video.scss
> +		.jw-state-paused .jw-controls {
you can put these styles inside `.jw-state-paused {`

2018-07-30 10:19 UTC, merged